// Ingredient seed data for the Vancouver / British Columbia MVP region.
//
// Provenance (see sources.ts and docs/methodology.md):
//   n      nutrition per 100 g of the purchase form — ESTIMATED: approximate USDA
//          FoodData Central (SR Legacy) reference values, not re-checked entry by entry.
//   price  current BC retail price — ESTIMATED by Base for 2026; not yet calibrated
//          against Statistics Canada table 18-10-0245-01.
//   season BC availability by month, Jan..Dec, one digit 0-9 (9 = peak) — ESTIMATED
//          from general knowledge of BC growing and storage seasons.
//   uses   culinary use cases — Base editorial catalogue (ESTIMATED).
//
// Nothing here is VERIFIED. The interface says so.

export type Category =
  | 'protein' | 'legume' | 'grain' | 'vegetable' | 'green' | 'aromatic'
  | 'fruit' | 'dairy' | 'pantry' | 'herb';

export type Texture =
  | 'grains' | 'beans' | 'chunks' | 'wedges' | 'leaves' | 'rings' | 'slices'
  | 'florets' | 'cream' | 'cubes' | 'strands' | 'berries' | 'cloves' | 'whole' | 'shreds';

export interface IngredientSeed {
  slug: string;
  name: string;
  category: Category;
  family: string;
  unit: 'g' | 'kg' | 'each' | 'bunch' | 'dozen' | 'ml' | 'l';
  storage: 'pantry' | 'cool_dark' | 'fridge' | 'freezer';
  shelf: number;                 // days, as handed over
  serving: number;               // grams per serving, purchase form
  purchase: string;              // form that price + nutrition refer to
  prep: string;                  // how Base hands it over
  container: boolean;
  description: string;
  why: string;                   // editorial — "Why Base likes it"
  visual: [color: string, accent: string, texture: Texture];
  n: [kcal: number, protein: number, carbs: number, fat: number, fiber: number, sodium: number];
  price: [amount: number, unit: 'kg' | 'dozen' | 'bunch' | 'each' | 'l'];
  supplier: string;              // supplier slug (all demo suppliers)
  season: string;                // 12 digits, Jan..Dec
  bcGrown: boolean;              // produced in BC when in season
  uses: string[];
  conversions?: Record<string, number>;   // grams per non-kg unit
  pantryBasic?: boolean;         // assumed at home; not sold in a Base, not scored
}

export const INGREDIENTS: IngredientSeed[] = [
  // ---------------------------------------------------------------- proteins
  {
    slug: 'chicken-thighs', name: 'Chicken thighs', category: 'protein', family: 'poultry',
    unit: 'kg', storage: 'fridge', shelf: 3, serving: 130, purchase: 'boneless, skinless, raw',
    prep: 'trimmed and packed raw in a sealed container', container: true,
    description: 'Boneless, skinless thighs from BC-raised chicken.',
    why: 'Thighs stay juicy whether you roast, braise, grill or stir-fry them, and they cost less than breasts. One batch can become curry on Monday and wraps on Wednesday.',
    visual: ['#E9B79A', '#D49577', 'chunks'],
    n: [121, 19.7, 0, 4.1, 0, 95], price: [15.4, 'kg'], supplier: 'bc-poultry-eggs-demo',
    season: '999999999999', bcGrown: true,
    uses: ['lunch', 'dinner', 'curry', 'stir-fry', 'wrap', 'bowl', 'stew', 'sheet-pan', 'sandwich', 'soup', 'roasting', 'grilling', 'braising', 'salad'],
  },
  {
    slug: 'chicken-breast', name: 'Chicken breast', category: 'protein', family: 'poultry',
    unit: 'kg', storage: 'fridge', shelf: 3, serving: 130, purchase: 'boneless, skinless, raw',
    prep: 'trimmed and packed raw in a sealed container', container: true,
    description: 'Lean boneless breast from BC-raised chicken.',
    why: 'Lean and quick to cook. Less forgiving than thighs and a little pricier per serving, so it is useful rather than essential.',
    visual: ['#F0C9B2', '#DDAA8F', 'slices'],
    n: [120, 22.5, 0, 2.6, 0, 45], price: [18.7, 'kg'], supplier: 'bc-poultry-eggs-demo',
    season: '999999999999', bcGrown: true,
    uses: ['lunch', 'dinner', 'stir-fry', 'wrap', 'salad', 'sandwich', 'bowl', 'grilling', 'sheet-pan', 'pasta'],
  },
  {
    slug: 'eggs', name: 'Eggs', category: 'protein', family: 'eggs',
    unit: 'dozen', storage: 'fridge', shelf: 21, serving: 100, purchase: 'whole, raw (about two large eggs)',
    prep: 'in a reusable carton', container: false,
    description: 'Large eggs from BC farms.',
    why: 'The fastest protein in the kitchen: breakfast, a hash, a fried egg on rice, or the thing that turns leftovers into dinner.',
    visual: ['#F4EEE2', '#F2B632', 'whole'],
    n: [143, 12.6, 0.7, 9.5, 0, 142], price: [5.2, 'dozen'], supplier: 'bc-poultry-eggs-demo',
    season: '999999999999', bcGrown: true, conversions: { dozen: 600 },
    uses: ['breakfast', 'lunch', 'dinner', 'snack', 'hash', 'salad', 'sandwich', 'baking', 'stir-fry', 'bowl', 'sauce'],
  },
  {
    slug: 'ground-turkey', name: 'Ground turkey', category: 'protein', family: 'poultry',
    unit: 'kg', storage: 'fridge', shelf: 2, serving: 120, purchase: 'lean, raw',
    prep: 'packed raw in a sealed container', container: true,
    description: 'Lean ground turkey.',
    why: 'Quick and lean for sauces, lettuce wraps and stir-fries.',
    visual: ['#DDA88E', '#C78C71', 'shreds'],
    n: [150, 18.7, 0, 8.3, 0, 69], price: [13.2, 'kg'], supplier: 'bc-poultry-eggs-demo',
    season: '888888888899', bcGrown: true,
    uses: ['lunch', 'dinner', 'pasta', 'wrap', 'stir-fry', 'bowl', 'sauce', 'soup', 'sauteing'],
  },
  {
    slug: 'pork-shoulder', name: 'Pork shoulder', category: 'protein', family: 'pork',
    unit: 'kg', storage: 'fridge', shelf: 3, serving: 130, purchase: 'boneless, raw',
    prep: 'cut into large pieces for braising', container: true,
    description: 'Boneless pork shoulder for slow cooking.',
    why: 'One slow braise on the weekend gives you tacos, rice bowls and sandwiches for days.',
    visual: ['#D9907E', '#EBC2B4', 'chunks'],
    n: [148, 19.6, 0, 7.1, 0, 79], price: [9.9, 'kg'], supplier: 'bc-meats-demo',
    season: '888888888888', bcGrown: true,
    uses: ['dinner', 'lunch', 'stew', 'wrap', 'sandwich', 'braising', 'roasting', 'bowl'],
  },
  {
    slug: 'ground-beef', name: 'Ground beef', category: 'protein', family: 'beef',
    unit: 'kg', storage: 'fridge', shelf: 2, serving: 120, purchase: '85% lean, raw',
    prep: 'packed raw in a sealed container', container: true,
    description: 'Medium ground beef.',
    why: 'Familiar and flexible for sauces and chili, though richer and pricier per gram of protein than poultry or legumes.',
    visual: ['#A8463E', '#C46A5E', 'shreds'],
    n: [215, 18.6, 0, 15.0, 0, 66], price: [13.8, 'kg'], supplier: 'bc-meats-demo',
    season: '888888888888', bcGrown: true,
    uses: ['dinner', 'lunch', 'pasta', 'sauce', 'wrap', 'stew', 'sauteing', 'grilling'],
  },
  {
    slug: 'firm-tofu', name: 'Firm tofu', category: 'protein', family: 'soy',
    unit: 'kg', storage: 'fridge', shelf: 7, serving: 120, purchase: 'firm, packed in water',
    prep: 'drained and pressed', container: true,
    description: 'Firm tofu made from Canadian soybeans.',
    why: 'Takes on any flavour, crisps beautifully, and costs less per serving than most meat.',
    visual: ['#F3ECDA', '#E0D5BB', 'cubes'],
    n: [144, 17.3, 2.8, 8.7, 2.3, 14], price: [7.5, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '888888888888', bcGrown: false,
    uses: ['breakfast', 'lunch', 'dinner', 'stir-fry', 'bowl', 'curry', 'wrap', 'salad', 'sauteing', 'baking', 'grilling'],
  },
  {
    slug: 'sockeye-salmon', name: 'Sockeye salmon', category: 'protein', family: 'fish',
    unit: 'kg', storage: 'freezer', shelf: 2, serving: 130, purchase: 'fillet, raw',
    prep: 'portioned fillets', container: true,
    description: 'Wild BC sockeye fillet.',
    why: 'Exceptional, and worth having sometimes. It costs about twice as much per serving as chicken, which is why Base offers it as an add-on.',
    visual: ['#F08A63', '#F7C2A8', 'slices'],
    n: [131, 22.3, 0, 4.7, 0, 47], price: [33.0, 'kg'], supplier: 'coastal-seafood-demo',
    season: '444445899544', bcGrown: true,
    uses: ['lunch', 'dinner', 'bowl', 'salad', 'grilling', 'roasting', 'sheet-pan'],
  },

  // ---------------------------------------------------------------- legumes
  {
    slug: 'chickpeas', name: 'Chickpeas', category: 'legume', family: 'pulse',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 60, purchase: 'dry',
    prep: 'soaked and cooked for you (about 2.4× the dry weight)', container: true,
    description: 'Canadian chickpeas, cooked and ready to use.',
    why: 'Cheap, filling and protein-rich. They roast until crisp, blend into a dip, bulk out a curry or anchor a salad.',
    visual: ['#E6C27A', '#CFA45A', 'beans'],
    n: [378, 20.5, 63.0, 6.0, 12.2, 24], price: [4.4, 'kg'], supplier: 'prairie-pulses-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'snack', 'salad', 'soup', 'bowl', 'curry', 'wrap', 'stew', 'dip', 'roasting', 'grain-salad'],
  },
  {
    slug: 'black-beans', name: 'Black beans', category: 'legume', family: 'pulse',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 60, purchase: 'dry',
    prep: 'soaked and cooked for you', container: true,
    description: 'Black beans, cooked and ready to use.',
    why: 'Earthy and hearty: the base of a burrito bowl, a soup or breakfast eggs.',
    visual: ['#2C2A2E', '#4A4650', 'beans'],
    n: [341, 21.6, 62.4, 1.4, 15.5, 5], price: [4.4, 'kg'], supplier: 'prairie-pulses-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'breakfast', 'bowl', 'wrap', 'soup', 'stew', 'salad', 'dip'],
  },
  {
    slug: 'red-lentils', name: 'Red lentils', category: 'legume', family: 'pulse',
    unit: 'kg', storage: 'pantry', shelf: 180, serving: 60, purchase: 'dry',
    prep: 'rinsed, dry', container: true,
    description: 'Split red lentils from the Prairies.',
    why: 'They cook in 15 minutes without soaking and melt into soups and dals.',
    visual: ['#E57A45', '#D0622F', 'grains'],
    n: [358, 23.9, 63.1, 2.2, 10.8, 7], price: [4.8, 'kg'], supplier: 'prairie-pulses-demo',
    season: '999999999999', bcGrown: false,
    uses: ['lunch', 'dinner', 'soup', 'curry', 'stew', 'dip'],
  },
  {
    slug: 'green-lentils', name: 'Green lentils', category: 'legume', family: 'pulse',
    unit: 'kg', storage: 'pantry', shelf: 180, serving: 60, purchase: 'dry',
    prep: 'cooked for you', container: true,
    description: 'Canadian green lentils that hold their shape.',
    why: 'They hold their shape, so they work in salads and bowls as well as soups. Canada is one of the world’s biggest lentil producers.',
    visual: ['#7E7A44', '#625E34', 'grains'],
    n: [352, 24.6, 63.4, 1.1, 10.7, 6], price: [4.4, 'kg'], supplier: 'prairie-pulses-demo',
    season: '999999999999', bcGrown: false,
    uses: ['lunch', 'dinner', 'salad', 'soup', 'stew', 'bowl', 'grain-salad', 'side'],
  },
  {
    slug: 'navy-beans', name: 'White beans', category: 'legume', family: 'pulse',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 60, purchase: 'dry (navy)',
    prep: 'soaked and cooked for you', container: true,
    description: 'Small white beans, cooked and ready.',
    why: 'Creamy in soups and stews, good mashed on toast, and very good value.',
    visual: ['#F1EBDC', '#D9D0BC', 'beans'],
    n: [337, 22.3, 60.8, 1.5, 15.3, 5], price: [4.4, 'kg'], supplier: 'prairie-pulses-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'soup', 'stew', 'dip', 'salad', 'braising', 'baking'],
  },

  // ---------------------------------------------------------------- grains
  {
    slug: 'brown-rice', name: 'Brown rice', category: 'grain', family: 'rice',
    unit: 'kg', storage: 'pantry', shelf: 180, serving: 70, purchase: 'dry',
    prep: 'portioned, uncooked', container: true,
    description: 'Long-grain brown rice.',
    why: 'Cook one big pot on Sunday and it is the base of bowls, stir-fries and curries all week.',
    visual: ['#C9A877', '#B39160', 'grains'],
    n: [370, 7.9, 77.2, 2.9, 3.5, 7], price: [4.0, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'bowl', 'stir-fry', 'curry', 'side', 'grain-salad', 'soup', 'wrap'],
  },
  {
    slug: 'rolled-oats', name: 'Rolled oats', category: 'grain', family: 'oats',
    unit: 'kg', storage: 'pantry', shelf: 180, serving: 50, purchase: 'dry',
    prep: 'portioned', container: true,
    description: 'Canadian rolled oats.',
    why: 'Breakfast handled. Cheap, filling and high in fibre, but useful mostly in the morning.',
    visual: ['#E3D2AE', '#CDB78C', 'grains'],
    n: [379, 13.2, 67.7, 6.5, 10.1, 6], price: [3.3, 'kg'], supplier: 'prairie-pulses-demo',
    season: '999999999999', bcGrown: false,
    uses: ['breakfast', 'snack', 'baking', 'blending'],
  },
  {
    slug: 'pearl-barley', name: 'Pearl barley', category: 'grain', family: 'barley',
    unit: 'kg', storage: 'pantry', shelf: 180, serving: 60, purchase: 'dry',
    prep: 'portioned, uncooked', container: true,
    description: 'Pearl barley from the Prairies.',
    why: 'Chewy, nutty and very high in fibre. Excellent in soups and grain salads.',
    visual: ['#E1CFA4', '#C9B585', 'grains'],
    n: [352, 9.9, 77.7, 1.2, 15.6, 9], price: [3.5, 'kg'], supplier: 'prairie-pulses-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'soup', 'stew', 'grain-salad', 'bowl', 'side'],
  },
  {
    slug: 'whole-wheat-pasta', name: 'Whole wheat pasta', category: 'grain', family: 'wheat',
    unit: 'kg', storage: 'pantry', shelf: 365, serving: 85, purchase: 'dry',
    prep: 'portioned', container: true,
    description: 'Whole wheat short pasta.',
    why: 'Dinner in 12 minutes. Pairs with almost any vegetable in the Base.',
    visual: ['#C79A5B', '#B0844A', 'strands'],
    n: [348, 14.6, 75.0, 1.4, 9.2, 8], price: [4.4, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '888888888888', bcGrown: false,
    uses: ['lunch', 'dinner', 'pasta', 'salad', 'soup', 'baking'],
  },
  {
    slug: 'quinoa', name: 'Quinoa', category: 'grain', family: 'quinoa',
    unit: 'kg', storage: 'pantry', shelf: 365, serving: 60, purchase: 'dry',
    prep: 'rinsed, uncooked', container: true,
    description: 'White quinoa.',
    why: 'High in protein for a grain and fast to cook, but costs about three times as much as rice per serving.',
    visual: ['#E8D8AE', '#C9B07E', 'grains'],
    n: [368, 14.1, 64.2, 6.1, 7.0, 5], price: [11.0, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '777777777777', bcGrown: false,
    uses: ['breakfast', 'lunch', 'dinner', 'bowl', 'grain-salad', 'salad', 'side'],
  },

  // ---------------------------------------------------------------- vegetables
  {
    slug: 'potatoes', name: 'Potatoes', category: 'vegetable', family: 'tuber',
    unit: 'kg', storage: 'cool_dark', shelf: 7, serving: 200, purchase: 'whole, raw',
    prep: 'washed and cut into wedges', container: true,
    description: 'Yellow potatoes from the Fraser Valley.',
    why: 'They are inexpensive, store well, work across cooking styles and can form the base of several meals: roasted, hashed, mashed, in soup or curry.',
    visual: ['#E7C98B', '#C9A15E', 'wedges'],
    n: [77, 2.0, 17.5, 0.1, 2.1, 6], price: [2.4, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '776556899988', bcGrown: true,
    uses: ['breakfast', 'lunch', 'dinner', 'soup', 'curry', 'hash', 'stew', 'side', 'sheet-pan', 'salad', 'roasting', 'baking', 'mashing', 'braising'],
  },
  {
    slug: 'sweet-potatoes', name: 'Sweet potatoes', category: 'vegetable', family: 'tuber',
    unit: 'kg', storage: 'cool_dark', shelf: 7, serving: 180, purchase: 'whole, raw',
    prep: 'peeled and cubed', container: true,
    description: 'Orange-fleshed sweet potatoes.',
    why: 'Sweet and fibre-rich, great roasted or in curry. Mostly imported, so they score lower on local availability.',
    visual: ['#E58A3F', '#C96B2A', 'cubes'],
    n: [86, 1.6, 20.1, 0.1, 3.0, 55], price: [4.2, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '666666666666', bcGrown: false,
    uses: ['breakfast', 'lunch', 'dinner', 'soup', 'curry', 'hash', 'bowl', 'side', 'sheet-pan', 'roasting', 'baking', 'mashing'],
  },
  {
    slug: 'carrots', name: 'Carrots', category: 'vegetable', family: 'root',
    unit: 'kg', storage: 'fridge', shelf: 10, serving: 100, purchase: 'whole, raw',
    prep: 'peeled and cut into batons', container: true,
    description: 'Fraser Valley carrots.',
    why: 'They work raw, roasted, braised or blended into soup, keep for weeks and are among the cheapest vegetables per serving.',
    visual: ['#EE8A2F', '#D06A1C', 'rings'],
    n: [41, 0.9, 9.6, 0.2, 2.8, 69], price: [2.6, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '776556899988', bcGrown: true,
    uses: ['lunch', 'dinner', 'snack', 'salad', 'soup', 'bowl', 'stir-fry', 'curry', 'stew', 'side', 'sheet-pan', 'roasting', 'raw', 'pickling', 'braising', 'blending'],
  },
  {
    slug: 'beets', name: 'Beets', category: 'vegetable', family: 'root',
    unit: 'kg', storage: 'fridge', shelf: 10, serving: 120, purchase: 'whole, raw',
    prep: 'roasted and peeled', container: true,
    description: 'Red beets.',
    why: 'Sweet and earthy. Roast once and use them in salads, bowls and dips.',
    visual: ['#8E2443', '#B23A5E', 'cubes'],
    n: [43, 1.6, 9.6, 0.2, 2.8, 78], price: [3.3, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '665556899987', bcGrown: true,
    uses: ['lunch', 'dinner', 'salad', 'soup', 'bowl', 'side', 'roasting', 'raw', 'pickling', 'dip'],
  },
  {
    slug: 'parsnips', name: 'Parsnips', category: 'vegetable', family: 'root',
    unit: 'kg', storage: 'fridge', shelf: 10, serving: 120, purchase: 'whole, raw',
    prep: 'peeled and cut into batons', container: true,
    description: 'Parsnips, sweetest after the first frost.',
    why: 'A cold-weather staple that turns sweet and nutty when roasted.',
    visual: ['#EADFC3', '#CDBF9A', 'rings'],
    n: [75, 1.2, 18.0, 0.3, 4.9, 10], price: [4.8, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '887533346899', bcGrown: true,
    uses: ['dinner', 'soup', 'stew', 'side', 'sheet-pan', 'roasting', 'mashing', 'baking'],
  },
  {
    slug: 'butternut-squash', name: 'Butternut squash', category: 'vegetable', family: 'squash',
    unit: 'kg', storage: 'cool_dark', shelf: 7, serving: 180, purchase: 'whole, raw',
    prep: 'peeled, seeded and cubed', container: true,
    description: 'Butternut squash from BC farms.',
    why: 'The fall workhorse. Roast it for bowls, blend it into soup or stir it into pasta and curry. Base does the peeling.',
    visual: ['#F0A13B', '#D9802A', 'cubes'],
    n: [45, 1.0, 11.7, 0.1, 2.0, 4], price: [3.3, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '653222237998', bcGrown: true,
    uses: ['lunch', 'dinner', 'soup', 'curry', 'bowl', 'pasta', 'side', 'sheet-pan', 'roasting', 'baking', 'blending', 'stew'],
  },
  {
    slug: 'green-cabbage', name: 'Green cabbage', category: 'vegetable', family: 'brassica',
    unit: 'kg', storage: 'fridge', shelf: 14, serving: 100, purchase: 'whole head, raw',
    prep: 'trimmed and shredded', container: true,
    description: 'Green cabbage.',
    why: 'Very cheap, keeps for weeks and goes from crunchy slaw to silky braise.',
    visual: ['#B9D58C', '#8DB566', 'shreds'],
    n: [25, 1.3, 5.8, 0.1, 2.5, 18], price: [2.2, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '765556789998', bcGrown: true,
    uses: ['lunch', 'dinner', 'salad', 'soup', 'stir-fry', 'wrap', 'stew', 'side', 'raw', 'pickling', 'braising', 'sauteing'],
  },
  {
    slug: 'cauliflower', name: 'Cauliflower', category: 'vegetable', family: 'brassica',
    unit: 'kg', storage: 'fridge', shelf: 7, serving: 120, purchase: 'head, raw',
    prep: 'cut into florets', container: true,
    description: 'Cauliflower.',
    why: 'Roasts golden, soaks up curry and can be blended into a creamy soup.',
    visual: ['#F1EBDA', '#D9CFB4', 'florets'],
    n: [25, 1.9, 5.0, 0.3, 2.0, 30], price: [5.5, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '333457899853', bcGrown: true,
    uses: ['lunch', 'dinner', 'curry', 'bowl', 'soup', 'side', 'sheet-pan', 'roasting', 'raw', 'mashing', 'stir-fry'],
  },
  {
    slug: 'broccoli', name: 'Broccoli', category: 'vegetable', family: 'brassica',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 100, purchase: 'crowns, raw',
    prep: 'cut into florets', container: true,
    description: 'Broccoli crowns.',
    why: 'Fast to cook and nutritionally useful. Good in stir-fries, pasta and on a sheet pan.',
    visual: ['#4E8A3B', '#3A6E2C', 'florets'],
    n: [34, 2.8, 6.6, 0.4, 2.6, 33], price: [5.8, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '333458999753', bcGrown: true,
    uses: ['lunch', 'dinner', 'stir-fry', 'bowl', 'pasta', 'side', 'sheet-pan', 'roasting', 'steaming', 'soup', 'salad'],
  },
  {
    slug: 'brussels-sprouts', name: 'Brussels sprouts', category: 'vegetable', family: 'brassica',
    unit: 'kg', storage: 'fridge', shelf: 7, serving: 100, purchase: 'trimmed, raw',
    prep: 'trimmed and halved', container: true,
    description: 'Brussels sprouts.',
    why: 'Wonderful roasted, but they suit fewer kinds of dishes than cabbage and cost more.',
    visual: ['#7EAA4A', '#5C8A33', 'whole'],
    n: [43, 3.4, 9.0, 0.3, 3.8, 25], price: [7.7, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '653222235899', bcGrown: true,
    uses: ['dinner', 'side', 'sheet-pan', 'roasting', 'salad', 'sauteing', 'hash'],
  },
  {
    slug: 'zucchini', name: 'Zucchini', category: 'vegetable', family: 'squash',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 120, purchase: 'whole, raw',
    prep: 'cut into half-moons', container: true,
    description: 'Summer zucchini.',
    why: 'Summer’s most generous vegetable: grill it, toss it into pasta or bake it.',
    visual: ['#6E9A44', '#DDE5B5', 'slices'],
    n: [17, 1.2, 3.1, 0.3, 1.0, 8], price: [4.8, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '222336998532', bcGrown: true,
    uses: ['lunch', 'dinner', 'pasta', 'stir-fry', 'side', 'sheet-pan', 'grilling', 'sauteing', 'baking', 'salad'],
  },
  {
    slug: 'tomatoes', name: 'Tomatoes', category: 'vegetable', family: 'nightshade',
    unit: 'kg', storage: 'cool_dark', shelf: 5, serving: 120, purchase: 'whole, raw',
    prep: 'whole, ripe (kept out of the fridge)', container: false,
    description: 'Field and greenhouse tomatoes from BC.',
    why: 'In season they are the flavour builder: raw in salads, roasted into sauce or cooked into curry.',
    visual: ['#D9432F', '#F07A55', 'wedges'],
    n: [18, 0.9, 3.9, 0.2, 1.2, 5], price: [5.5, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '335678999753', bcGrown: true,
    uses: ['breakfast', 'lunch', 'dinner', 'salad', 'sauce', 'sandwich', 'pasta', 'soup', 'curry', 'raw', 'roasting', 'stew', 'wrap'],
  },
  {
    slug: 'bell-peppers', name: 'Red bell peppers', category: 'vegetable', family: 'nightshade',
    unit: 'kg', storage: 'fridge', shelf: 7, serving: 100, purchase: 'whole, raw',
    prep: 'seeded and cut into strips', container: true,
    description: 'Sweet red peppers from BC greenhouses.',
    why: 'Sweet and crunchy raw, and silky when roasted. Good in stir-fries, wraps and sheet-pan dinners.',
    visual: ['#D6352A', '#F2633F', 'slices'],
    n: [31, 1.0, 6.0, 0.3, 2.1, 4], price: [7.7, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '334678899753', bcGrown: true,
    uses: ['lunch', 'dinner', 'snack', 'salad', 'stir-fry', 'wrap', 'sheet-pan', 'raw', 'roasting', 'grilling', 'dip'],
  },
  {
    slug: 'sweet-corn', name: 'Sweet corn', category: 'vegetable', family: 'grass',
    unit: 'each', storage: 'fridge', shelf: 3, serving: 150, purchase: 'on the cob, raw',
    prep: 'husked', container: false,
    description: 'Late-summer sweet corn.',
    why: 'Pure late summer. It is only worth buying for a few weeks a year, and the availability score reflects that.',
    visual: ['#F2C94C', '#E2B22F', 'grains'],
    n: [86, 3.3, 19.0, 1.4, 2.0, 15], price: [0.99, 'each'], supplier: 'fraser-valley-produce-demo',
    season: '111112798411', bcGrown: true, conversions: { each: 300 },
    uses: ['lunch', 'dinner', 'salad', 'soup', 'side', 'grilling', 'steaming', 'bowl'],
  },
  {
    slug: 'green-beans', name: 'Green beans', category: 'vegetable', family: 'bean',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 100, purchase: 'whole, raw',
    prep: 'topped and tailed', container: true,
    description: 'Summer green beans.',
    why: 'Crisp, quick and good in salads, stir-fries and curry.',
    visual: ['#5E9A3E', '#4A7E30', 'strands'],
    n: [31, 1.8, 7.0, 0.2, 2.7, 6], price: [8.8, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '222235899532', bcGrown: true,
    uses: ['dinner', 'side', 'stir-fry', 'salad', 'steaming', 'sauteing', 'curry'],
  },
  {
    slug: 'snap-peas', name: 'Peas', category: 'vegetable', family: 'bean',
    unit: 'kg', storage: 'fridge', shelf: 4, serving: 80, purchase: 'shelled, raw',
    prep: 'shelled', container: true,
    description: 'Fresh spring peas.',
    why: 'Sweet, green and fleeting. Use them in pasta, soup and salads in early summer.',
    visual: ['#7DBA4A', '#5E9A34', 'beans'],
    n: [81, 5.4, 14.5, 0.4, 5.1, 5], price: [9.9, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '222379963222', bcGrown: true,
    uses: ['lunch', 'dinner', 'pasta', 'soup', 'salad', 'side', 'curry', 'stir-fry', 'blending', 'raw'],
  },
  {
    slug: 'radishes', name: 'Radishes', category: 'vegetable', family: 'brassica',
    unit: 'kg', storage: 'fridge', shelf: 7, serving: 60, purchase: 'trimmed, raw',
    prep: 'trimmed and washed', container: true,
    description: 'Spring radishes.',
    why: 'Peppery crunch for salads, quick pickles and sandwiches.',
    visual: ['#D84A6A', '#F6E9EC', 'slices'],
    n: [16, 0.7, 3.4, 0.1, 1.6, 39], price: [6.6, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '223799887643', bcGrown: true,
    uses: ['lunch', 'snack', 'salad', 'raw', 'pickling', 'roasting', 'sandwich'],
  },
  {
    slug: 'cremini-mushrooms', name: 'Cremini mushrooms', category: 'vegetable', family: 'fungi',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 80, purchase: 'whole, raw',
    prep: 'cleaned and sliced', container: true,
    description: 'Cremini mushrooms grown indoors in BC year-round.',
    why: 'Deep, savoury flavour for pasta, stir-fries and breakfast, and grown in BC all year.',
    visual: ['#B08A68', '#8C6A4C', 'slices'],
    n: [22, 2.5, 4.3, 0.1, 0.6, 6], price: [11.0, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '888888888888', bcGrown: true,
    uses: ['breakfast', 'lunch', 'dinner', 'pasta', 'stir-fry', 'soup', 'stew', 'sauteing', 'roasting', 'bowl', 'sandwich'],
  },
  {
    slug: 'asparagus', name: 'Asparagus', category: 'vegetable', family: 'asparagus',
    unit: 'kg', storage: 'fridge', shelf: 4, serving: 100, purchase: 'spears, raw',
    prep: 'trimmed', container: true,
    description: 'Spring asparagus.',
    why: 'The first green of spring. Short season, high price outside it.',
    visual: ['#6F9F47', '#557F35', 'strands'],
    n: [20, 2.2, 3.9, 0.1, 2.1, 2], price: [11.0, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '112799521111', bcGrown: true,
    uses: ['lunch', 'dinner', 'side', 'pasta', 'salad', 'roasting', 'grilling', 'steaming'],
  },

  // ---------------------------------------------------------------- greens
  {
    slug: 'kale', name: 'Kale', category: 'green', family: 'brassica-leaf',
    unit: 'bunch', storage: 'fridge', shelf: 6, serving: 60, purchase: 'leaves, raw',
    prep: 'washed, de-stemmed and torn', container: true,
    description: 'Lacinato and curly kale from BC farms.',
    why: 'Hardy enough to grow in BC most of the year, sturdy enough to last the week, and useful in salads, soups, pasta and hash.',
    visual: ['#3F6B3A', '#5E8C4E', 'leaves'],
    n: [49, 4.3, 8.8, 0.9, 3.6, 38], price: [2.49, 'bunch'], supplier: 'fraser-valley-produce-demo',
    season: '777788889998', bcGrown: true, conversions: { bunch: 300 },
    uses: ['breakfast', 'lunch', 'dinner', 'salad', 'soup', 'stew', 'bowl', 'pasta', 'sauteing', 'raw', 'blending', 'hash'],
  },
  {
    slug: 'spinach', name: 'Spinach', category: 'green', family: 'amaranth-leaf',
    unit: 'kg', storage: 'fridge', shelf: 4, serving: 60, purchase: 'leaves, raw',
    prep: 'washed and dried', container: true,
    description: 'Tender spinach leaves.',
    why: 'It wilts into almost anything, but it is delicate, short-lived and pricier than kale.',
    visual: ['#3E7A3A', '#5C9A4E', 'leaves'],
    n: [23, 2.9, 3.6, 0.4, 2.2, 79], price: [13.2, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '445897568864', bcGrown: true,
    uses: ['breakfast', 'lunch', 'dinner', 'salad', 'soup', 'curry', 'pasta', 'sauteing', 'raw', 'blending', 'wrap', 'sandwich'],
  },
  {
    slug: 'swiss-chard', name: 'Swiss chard', category: 'green', family: 'amaranth-leaf',
    unit: 'bunch', storage: 'fridge', shelf: 5, serving: 70, purchase: 'leaves and stems, raw',
    prep: 'washed; stems and leaves separated', container: true,
    description: 'Rainbow chard.',
    why: 'Two vegetables in one: tender leaves and crunchy stems. Excellent braised.',
    visual: ['#4F7D3E', '#C2385A', 'leaves'],
    n: [19, 1.8, 3.7, 0.2, 1.6, 213], price: [2.99, 'bunch'], supplier: 'fraser-valley-produce-demo',
    season: '333467899863', bcGrown: true, conversions: { bunch: 350 },
    uses: ['lunch', 'dinner', 'soup', 'stew', 'pasta', 'sauteing', 'side', 'braising'],
  },
  {
    slug: 'romaine', name: 'Romaine', category: 'green', family: 'lettuce',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 80, purchase: 'leaves, raw',
    prep: 'washed and dried', container: true,
    description: 'Romaine hearts.',
    why: 'Crisp and refreshing, but it can only be eaten raw, which limits its versatility.',
    visual: ['#8CC063', '#B9DC8E', 'leaves'],
    n: [17, 1.2, 3.3, 0.3, 2.1, 8], price: [4.4, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '222478999752', bcGrown: true,
    uses: ['lunch', 'salad', 'wrap', 'sandwich', 'raw', 'grilling'],
  },

  // ---------------------------------------------------------------- aromatics
  {
    slug: 'yellow-onions', name: 'Onions', category: 'aromatic', family: 'allium',
    unit: 'kg', storage: 'cool_dark', shelf: 7, serving: 60, purchase: 'whole, raw',
    prep: 'peeled and diced', container: true,
    description: 'Yellow storage onions.',
    why: 'Nearly every savoury dish starts here. Base dices them so you can skip the most tedious step.',
    visual: ['#EAD8B4', '#C9A97A', 'rings'],
    n: [40, 1.1, 9.3, 0.1, 1.7, 4], price: [2.4, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '877655789998', bcGrown: true,
    uses: ['breakfast', 'lunch', 'dinner', 'soup', 'curry', 'stir-fry', 'hash', 'stew', 'sauce', 'salad', 'roasting', 'sauteing', 'pickling', 'braising', 'wrap'],
  },
  {
    slug: 'garlic', name: 'Garlic', category: 'aromatic', family: 'allium',
    unit: 'kg', storage: 'cool_dark', shelf: 14, serving: 6, purchase: 'whole bulbs',
    prep: 'peeled cloves', container: true,
    description: 'BC hardneck garlic.',
    why: 'A few cloves make everything taste like you meant it. BC garlic stores well from summer into winter.',
    visual: ['#F2EDE1', '#D8CFBD', 'cloves'],
    n: [149, 6.4, 33.1, 0.5, 2.1, 17], price: [13.2, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '665433789998', bcGrown: true,
    uses: ['lunch', 'dinner', 'soup', 'curry', 'stir-fry', 'stew', 'sauce', 'pasta', 'dip', 'roasting', 'sauteing', 'braising'],
  },
  {
    slug: 'leeks', name: 'Leeks', category: 'aromatic', family: 'allium',
    unit: 'kg', storage: 'fridge', shelf: 10, serving: 80, purchase: 'trimmed, raw',
    prep: 'washed and sliced', container: true,
    description: 'Leeks for soups and braises.',
    why: 'A milder, sweeter onion that holds up in winter soups and braises.',
    visual: ['#B9D59A', '#F0F2DD', 'rings'],
    n: [61, 1.5, 14.2, 0.3, 1.8, 20], price: [6.6, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '876432236899', bcGrown: true,
    uses: ['lunch', 'dinner', 'soup', 'stew', 'pasta', 'braising', 'sauteing', 'side'],
  },
  {
    slug: 'ginger', name: 'Ginger', category: 'aromatic', family: 'ginger',
    unit: 'kg', storage: 'fridge', shelf: 21, serving: 5, purchase: 'root, raw',
    prep: 'peeled', container: true,
    description: 'Fresh ginger root.',
    why: 'Bright heat for stir-fries, curries and broths. Imported.',
    visual: ['#D8B67A', '#B8924F', 'slices'],
    n: [80, 1.8, 17.8, 0.8, 2.0, 13], price: [8.8, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '666666666666', bcGrown: false,
    uses: ['dinner', 'curry', 'stir-fry', 'soup', 'sauce', 'braising', 'blending'],
  },

  // ---------------------------------------------------------------- fruit
  {
    slug: 'apples', name: 'Apples', category: 'fruit', family: 'pome',
    unit: 'kg', storage: 'fridge', shelf: 21, serving: 150, purchase: 'whole, raw',
    prep: 'whole', container: false,
    description: 'Okanagan apples.',
    why: 'Snack, breakfast, slaw or a quick bake. BC apples store from fall right through spring.',
    visual: ['#C8392F', '#E8D8A0', 'wedges'],
    n: [52, 0.3, 13.8, 0.2, 2.4, 1], price: [4.4, 'kg'], supplier: 'okanagan-orchards-demo',
    season: '776543369998', bcGrown: true,
    uses: ['breakfast', 'snack', 'salad', 'baking', 'raw', 'side', 'sauce', 'roasting'],
  },
  {
    slug: 'pears', name: 'Pears', category: 'fruit', family: 'pome',
    unit: 'kg', storage: 'fridge', shelf: 10, serving: 150, purchase: 'whole, raw',
    prep: 'whole', container: false,
    description: 'Okanagan pears.',
    why: 'Fall’s other orchard fruit, lovely raw or roasted.',
    visual: ['#C9C46A', '#E8E3A8', 'wedges'],
    n: [57, 0.4, 15.2, 0.1, 3.1, 1], price: [4.8, 'kg'], supplier: 'okanagan-orchards-demo',
    season: '654322259987', bcGrown: true,
    uses: ['breakfast', 'snack', 'salad', 'baking', 'raw', 'roasting'],
  },
  {
    slug: 'blueberries', name: 'Blueberries', category: 'fruit', family: 'berry',
    unit: 'kg', storage: 'fridge', shelf: 5, serving: 80, purchase: 'fresh',
    prep: 'washed', container: true,
    description: 'Fraser Valley blueberries.',
    why: 'BC is one of the world’s great blueberry regions. They peak for a few weeks in midsummer.',
    visual: ['#3E4D7A', '#5A6A9A', 'berries'],
    n: [57, 0.7, 14.5, 0.3, 2.4, 1], price: [11.0, 'kg'], supplier: 'fraser-valley-produce-demo',
    season: '222223995222', bcGrown: true,
    uses: ['breakfast', 'snack', 'baking', 'raw', 'blending', 'salad'],
  },
  {
    slug: 'lemons', name: 'Lemons', category: 'fruit', family: 'citrus',
    unit: 'each', storage: 'fridge', shelf: 21, serving: 30, purchase: 'whole',
    prep: 'whole', container: false,
    description: 'Lemons (imported).',
    why: 'A squeeze of acid wakes up almost any dish.',
    visual: ['#F2D447', '#E8C02C', 'wedges'],
    n: [29, 1.1, 9.3, 0.3, 2.8, 2], price: [0.79, 'each'], supplier: 'pantry-wholesale-demo',
    season: '777777777777', bcGrown: false, conversions: { each: 110 },
    uses: ['lunch', 'dinner', 'salad', 'sauce', 'dip', 'baking', 'raw'],
  },

  // ---------------------------------------------------------------- dairy
  {
    slug: 'greek-yogurt', name: 'Plain Greek yogurt', category: 'dairy', family: 'cultured-dairy',
    unit: 'kg', storage: 'fridge', shelf: 14, serving: 150, purchase: 'plain, 2% milk fat',
    prep: 'in a returnable glass jar', container: true,
    description: 'Thick plain yogurt from BC milk.',
    why: 'Breakfast with fruit and oats, a cooling sauce for curry and spice, a marinade for chicken. The flavour builder you can eat with a spoon.',
    visual: ['#F7F4EC', '#E9E3D3', 'cream'],
    n: [73, 10.0, 3.9, 1.9, 0, 34], price: [8.8, 'kg'], supplier: 'bc-dairy-demo',
    season: '999999999999', bcGrown: true,
    uses: ['breakfast', 'snack', 'sauce', 'dip', 'curry', 'baking', 'blending', 'bowl', 'wrap'],
  },
  {
    slug: 'aged-cheddar', name: 'Aged cheddar', category: 'dairy', family: 'cheese',
    unit: 'kg', storage: 'fridge', shelf: 28, serving: 30, purchase: 'block',
    prep: 'block', container: true,
    description: 'Aged white cheddar from BC.',
    why: 'Wonderful, but rich and high in sodium. It makes the most sense as an optional add-on.',
    visual: ['#F0B43C', '#E09A22', 'cubes'],
    n: [403, 24.9, 1.3, 33.1, 0, 621], price: [22.0, 'kg'], supplier: 'bc-dairy-demo',
    season: '999999999999', bcGrown: true,
    uses: ['breakfast', 'lunch', 'snack', 'sandwich', 'pasta', 'baking', 'wrap'],
  },
  {
    slug: 'feta', name: 'Feta', category: 'dairy', family: 'cheese',
    unit: 'kg', storage: 'fridge', shelf: 21, serving: 30, purchase: 'block in brine',
    prep: 'in brine', container: true,
    description: 'Brined feta.',
    why: 'A salty, tangy finish for salads and bowls. A little goes a long way.',
    visual: ['#F6F2E6', '#E2DCCB', 'cubes'],
    n: [264, 14.2, 4.1, 21.3, 0, 917], price: [24.0, 'kg'], supplier: 'bc-dairy-demo',
    season: '888888888888', bcGrown: true,
    uses: ['lunch', 'salad', 'baking', 'wrap', 'dip', 'bowl'],
  },

  // ---------------------------------------------------------------- pantry / flavour
  {
    slug: 'crushed-tomatoes', name: 'Crushed tomatoes', category: 'pantry', family: 'nightshade',
    unit: 'l', storage: 'pantry', shelf: 365, serving: 120, purchase: 'canned',
    prep: 'in the can', container: false,
    description: 'Canned crushed tomatoes.',
    why: 'Summer’s tomatoes, on the shelf all winter. The fastest way to sauce, soup, braise or curry.',
    visual: ['#C0392B', '#D9584A', 'cream'],
    n: [32, 1.6, 7.3, 0.3, 1.9, 186], price: [3.13, 'l'], supplier: 'pantry-wholesale-demo',
    season: '999999999999', bcGrown: false,
    uses: ['lunch', 'dinner', 'sauce', 'soup', 'curry', 'stew', 'pasta', 'braising', 'baking'],
  },
  {
    slug: 'chanterelles', name: 'Chanterelles', category: 'vegetable', family: 'fungi',
    unit: 'kg', storage: 'fridge', shelf: 4, serving: 60, purchase: 'fresh, wild',
    prep: 'brushed clean', container: true,
    description: 'Wild BC chanterelles.',
    why: 'A fall luxury from BC forests. Too seasonal and too expensive to be part of the Base, and perfect as an add-on.',
    visual: ['#EBA531', '#D58A1C', 'slices'],
    n: [32, 1.5, 6.9, 0.5, 3.8, 9], price: [44.0, 'kg'], supplier: 'wild-forage-demo',
    season: '111111258961', bcGrown: true,
    uses: ['dinner', 'pasta', 'sauteing', 'soup'],
  },

  // ---------------------------------------------------------------- herbs
  {
    slug: 'parsley', name: 'Parsley', category: 'herb', family: 'umbellifer-herb',
    unit: 'bunch', storage: 'fridge', shelf: 7, serving: 10, purchase: 'leaves, fresh',
    prep: 'washed and dried', container: true,
    description: 'Flat-leaf parsley.',
    why: 'Fresh green brightness for salads, grains and sauces, at pennies per serving.',
    visual: ['#3E8A3A', '#5DAA4E', 'leaves'],
    n: [36, 3.0, 6.3, 0.8, 3.3, 56], price: [1.49, 'bunch'], supplier: 'fraser-valley-produce-demo',
    season: '444678999754', bcGrown: true, conversions: { bunch: 60 },
    uses: ['lunch', 'dinner', 'salad', 'sauce', 'soup', 'grain-salad', 'raw'],
  },
  {
    slug: 'cilantro', name: 'Cilantro', category: 'herb', family: 'umbellifer-herb',
    unit: 'bunch', storage: 'fridge', shelf: 5, serving: 10, purchase: 'leaves, fresh',
    prep: 'washed and dried', container: true,
    description: 'Fresh cilantro.',
    why: 'The finishing touch for curries, wraps and bowls.',
    visual: ['#4A9A44', '#6DB65E', 'leaves'],
    n: [23, 2.1, 3.7, 0.5, 2.8, 46], price: [1.49, 'bunch'], supplier: 'fraser-valley-produce-demo',
    season: '444678998654', bcGrown: true, conversions: { bunch: 60 },
    uses: ['lunch', 'dinner', 'salad', 'curry', 'wrap', 'sauce', 'raw'],
  },
  {
    slug: 'dill', name: 'Dill', category: 'herb', family: 'umbellifer-herb',
    unit: 'bunch', storage: 'fridge', shelf: 5, serving: 8, purchase: 'fronds, fresh',
    prep: 'washed and dried', container: true,
    description: 'Fresh dill.',
    why: 'Made for potatoes, yogurt sauces and quick pickles.',
    visual: ['#6A9F4A', '#8CBB66', 'strands'],
    n: [43, 3.5, 7.0, 1.1, 2.1, 61], price: [1.49, 'bunch'], supplier: 'fraser-valley-produce-demo',
    season: '333578998543', bcGrown: true, conversions: { bunch: 40 },
    uses: ['lunch', 'salad', 'sauce', 'dip', 'soup', 'pickling'],
  },

  // ---------------------------------------------------------------- pantry basics (assumed at home)
  {
    slug: 'canola-oil', name: 'Cooking oil', category: 'pantry', family: 'oil',
    unit: 'l', storage: 'pantry', shelf: 365, serving: 15, purchase: 'canola oil',
    prep: 'from your pantry', container: false, pantryBasic: true,
    description: 'Neutral cooking oil. Assumed to be in your kitchen; not part of a Base.',
    why: 'A pantry basic. Recipes assume you have oil, salt and pepper.',
    visual: ['#E8C547', '#D6AE2E', 'cream'],
    n: [884, 0, 0, 100, 0, 0], price: [5.5, 'l'], supplier: 'pantry-wholesale-demo',
    season: '999999999999', bcGrown: false, uses: ['sauteing', 'roasting'],
  },
  {
    slug: 'salt', name: 'Salt', category: 'pantry', family: 'mineral',
    unit: 'kg', storage: 'pantry', shelf: 3650, serving: 1, purchase: 'fine salt',
    prep: 'from your pantry', container: false, pantryBasic: true,
    description: 'Salt. Assumed to be in your kitchen; not part of a Base.',
    why: 'A pantry basic. Recipes assume you have oil, salt and pepper.',
    visual: ['#F2F0EA', '#DCD8CE', 'grains'],
    n: [0, 0, 0, 0, 0, 38758], price: [2.2, 'kg'], supplier: 'pantry-wholesale-demo',
    season: '999999999999', bcGrown: false, uses: [],
  },
];
