// Photos of each ingredient, add-on and recipe, from Wikimedia Commons and Openverse (Flickr) under free licences
// (public domain, CC0, CC BY, CC BY-SA). Chosen by hand for accuracy from candidates
// fetched by scripts/photos/candidates.ts; files are in public/photos/.
// They are representative photos, not pictures of Base's own food.

export interface PhotoSeed {
  alt: string; title: string; author: string; license: string; licenseUrl: string; sourceUrl: string;
  width: number; height: number;
  /** Where the photo was found: Wikimedia Commons, Flickr, rawpixel… */
  via: string;
}

export const PHOTOS: Record<string, PhotoSeed> = {
  "asparagus-spinach-barley-risotto": {
    "alt": "Risotto with asparagus",
    "title": "Asparagus Risotto",
    "author": "Katrin Gilger",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/26242865@N04/4562450879",
    "via": "Flickr",
    "width": 960,
    "height": 641
  },
  "breakfast-hash": {
    "alt": "A fried egg on a vegetable hash",
    "title": "Mmm... Spam hash with fried egg",
    "author": "jeffreyw",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/7927684@N03/7880929132",
    "via": "Flickr",
    "width": 960,
    "height": 636
  },
  "cauliflower-potato-curry": {
    "alt": "Cauliflower and potato curry (aloo gobi)",
    "title": "Aloo Gobi at Two Wolves Community Cantina, Chippendale: Sydney Food Blog Review",
    "author": "insatiablemunch",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/48041244@N05/21883116303",
    "via": "Flickr",
    "width": 683,
    "height": 1024
  },
  "charred-tomato-black-bean-bowls": {
    "alt": "A bowl of rice, black beans and fresh tomato",
    "title": "Giant burrito!",
    "author": "goblinbox_(queen_of_ad_hoc_bento)",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/25977089@N00/5347841613",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "chicken-barley-soup": {
    "alt": "Barley soup with meat and a spoon of sour cream",
    "title": "Vegetable pork barley soup with chicken livers and sour cream, by Silar 2010 I",
    "author": "Silar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=11823652",
    "via": "Wikimedia Commons",
    "width": 640,
    "height": 480
  },
  "crispy-chickpea-potato-bowl": {
    "alt": "A bowl of crispy roasted chickpeas",
    "title": "Chickpea Buddha Bowls",
    "author": "jules:stonesoup",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/58367355@N00/45091823365",
    "via": "Flickr",
    "width": 960,
    "height": 639
  },
  "green-chicken-curry": {
    "alt": "Green chicken curry with basil",
    "title": "thai green chicken curry",
    "author": "jules:stonesoup",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/58367355@N00/12830275973",
    "via": "Flickr",
    "width": 960,
    "height": 639
  },
  "kale-barley-minestrone": {
    "alt": "A bowl of minestrone",
    "title": "Cannellini, Mushroom, Leek, Celery, Carrot, Zucchini, Pasta Minestrone Soup - close - photo by Julia",
    "author": "avlxyz",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/10559879@N00/4947558897",
    "via": "Flickr",
    "width": 960,
    "height": 643
  },
  "roasted-cauliflower-barley-salad": {
    "alt": "Barley salad with roasted cauliflower and greens",
    "title": "Roasted cauliflower and herbed barley salad",
    "author": "veritatem",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/66722164@N00/20582519053",
    "via": "Flickr",
    "width": 960,
    "height": 960
  },
  "spiced-carrot-soup": {
    "alt": "Carrot soup with a spoon of yogurt",
    "title": "Carrot soup with Greek yogurt",
    "author": "stu_spivack",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=44943988",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 637
  },
  "squash-black-bean-chili": {
    "alt": "A bowl of black bean chili",
    "title": "Solar cooked vegetarian chili",
    "author": "EBKauai",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/13470115@N08/6734016371",
    "via": "Flickr",
    "width": 960,
    "height": 540
  },
  "chicken-barley-bowls-lemon-yogurt": {
    "alt": "A bowl of roast chicken with vegetables",
    "title": "Liat Portal for Foodie Disorder - Roasted chicken with cauliflower broccoli potatoes rice and salad",
    "author": "HaJunkiyada",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=183820849",
    "via": "Wikimedia Commons",
    "width": 900,
    "height": 1200
  },
  "crispy-tofu-cabbage-stir-fry": {
    "alt": "Tofu and cabbage stir-fry",
    "title": "Tomyum Vegetarian Fried Noodles - Mint Thai AUD9",
    "author": "avlxyz",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/10559879@N00/3517178007",
    "via": "Flickr",
    "width": 960,
    "height": 643
  },
  "eggs-garlicky-greens-chickpeas": {
    "alt": "Eggs cooked with greens",
    "title": "Scrambled eggs with green beans, pesto, and cheddar cheese",
    "author": "Laurel Fan",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/18295242@N00/7996344623",
    "via": "Flickr",
    "width": 765,
    "height": 1024
  },
  "lemon-garlic-chicken-sheet-pan": {
    "alt": "Roast chicken legs",
    "title": "Roasted chicken thighs",
    "author": "Neeta Lind",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/71132408@N00/11348618374",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "parsnip-cabbage-mushroom-tray": {
    "alt": "Roasted parsnips and potatoes",
    "title": "Parsnips",
    "author": "whatleydude",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/85318305@N00/6578192419",
    "via": "Flickr",
    "width": 960,
    "height": 540
  },
  "whole-wheat-pasta": {
    "alt": "Whole wheat penne",
    "title": "Whole wheat penne, cooked and uncooked",
    "author": "Ragesoss",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=3756604",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 642
  },
  "chicken-thighs": {
    "alt": "Raw boneless, skinless chicken thighs",
    "title": "Raw chicken thighs.jpg",
    "author": "gran",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raw_chicken_thighs.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "chicken-breast": {
    "alt": "Two raw boneless chicken breasts on a white plate",
    "title": "Raw chicken slices.jpg",
    "author": "kakyusei",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raw_chicken_slices.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "eggs": {
    "alt": "Brown eggs in a carton",
    "title": "Brown-eggs.jpg",
    "author": "Photos public domain.com",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brown-eggs.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "ground-turkey": {
    "alt": "Ground turkey browning in a pan",
    "title": "Ground turkey (4515834437).jpg",
    "author": "Michael Coté from Austin, Texas, Texas",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ground_turkey_(4515834437).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "pork-shoulder": {
    "alt": "Raw pork shoulder cut into large pieces",
    "title": "HK food ingredient red meat frozen pork chop raw butt steak October 2021 SS2 018.jpg",
    "author": "Presixlla MOON",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HK_food_ingredient_red_meat_frozen_pork_chop_raw_butt_steak_October_2021_SS2_018.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "ground-beef": {
    "alt": "Raw ground beef",
    "title": "Hakket-oksekoed.jpg",
    "author": "Gajda-13 at Danish Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hakket-oksekoed.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 689
  },
  "firm-tofu": {
    "alt": "A block of firm tofu",
    "title": "Japanese tofu 001.jpg",
    "author": "Ocdp",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Japanese_tofu_001.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "sockeye-salmon": {
    "alt": "Raw wild sockeye salmon, cut into a steak and fillets",
    "title": "Oncorhynchus nerka (RFEIMG-0186).jpg",
    "author": "The U.S. Food and Drug Administration",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_(RFEIMG-0186).jpg",
    "via": "Wikimedia Commons",
    "width": 633,
    "height": 438
  },
  "chickpeas": {
    "alt": "Cooked chickpeas",
    "title": "Garbanzos con allioli, gastronomía rural, comarca Maestrazgo.jpg",
    "author": "Juan Emilio Prades Bel",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garbanzos_con_allioli,_gastronom%C3%ADa_rural,_comarca_Maestrazgo.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "black-beans": {
    "alt": "Dry black turtle beans",
    "title": "Black Turtle Bean.jpg",
    "author": "Sanjay Acharya",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_Turtle_Bean.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "red-lentils": {
    "alt": "Dry red lentils",
    "title": "Split Red Lentil.jpg",
    "author": "Sanjay Acharya",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Split_Red_Lentil.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "green-lentils": {
    "alt": "Cooked lentils in a bowl",
    "title": "14. cooked lentils",
    "author": "jules:stonesoup",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/58367355@N00/6858972746",
    "via": "Flickr",
    "width": 960,
    "height": 672
  },
  "navy-beans": {
    "alt": "Small white beans in a colander",
    "title": "Porotos alubia blancos escurridos en colador de acero inoxidable.jpg",
    "author": "Horacio Cambeiro",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porotos_alubia_blancos_escurridos_en_colador_de_acero_inoxidable.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 759
  },
  "brown-rice": {
    "alt": "Uncooked brown rice",
    "title": "Germinated brown rice - long grain.jpg",
    "author": "Chouk Khmer",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Germinated_brown_rice_-_long_grain.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "rolled-oats": {
    "alt": "Rolled oats",
    "title": "Rolled oats 2.jpg",
    "author": "Yonygg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rolled_oats_2.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "pearl-barley": {
    "alt": "Pearl barley",
    "title": "Kasza jeczmienna 02.jpg",
    "author": "Agnieszka Kwiecień (Nova)",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kasza_jeczmienna_02.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "quinoa": {
    "alt": "Uncooked white quinoa",
    "title": "Quinoa closeup.jpg",
    "author": "Pom²",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quinoa_closeup.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 643
  },
  "potatoes": {
    "alt": "Cut potatoes",
    "title": "Cut Potatoes.jpg",
    "author": "Alabama Extension",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cut_Potatoes.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 594
  },
  "sweet-potatoes": {
    "alt": "Peeled sweet potatoes",
    "title": "sweet potatoes",
    "author": "Phil Denton",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/37475039@N04/4261105782",
    "via": "Flickr",
    "width": 768,
    "height": 1024
  },
  "carrots": {
    "alt": "Peeled carrot sticks",
    "title": "lactofermented carrot sticks",
    "author": "HealthHomeHappy.com",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/39794839@N03/4790925848",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "beets": {
    "alt": "Cooked, peeled beets",
    "title": "Liat Portal for Foodie Disorder - Cooked Boiled Beetroot.jpg",
    "author": "HaJunkiyada",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Cooked_Boiled_Beetroot.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "butternut-squash": {
    "alt": "Peeled, cubed butternut squash",
    "title": "Cubed butternut squash",
    "author": "trenttsd",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/84335369@N00/6153009721",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "green-cabbage": {
    "alt": "Shredded cabbage",
    "title": "Shredded Cabbage (Side Dish) in Taiwan.jpg",
    "author": "Ralff Nestor Nacor",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shredded_Cabbage_(Side_Dish)_in_Taiwan.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1275
  },
  "cauliflower": {
    "alt": "Raw cauliflower florets",
    "title": "Cauliflower florets.jpg",
    "author": "WordRidden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cauliflower_florets.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "broccoli": {
    "alt": "Raw broccoli florets",
    "title": "Broccoli florets on ice.jpg",
    "author": "Jeffery Martin",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Broccoli_florets_on_ice.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "brussels-sprouts": {
    "alt": "Washed Brussels sprouts in a colander",
    "title": "-2020-01-01 Brussel sprouts, Trimingham, Norfolk.JPG",
    "author": "Kolforn (Kolforn) I'd appreciate if you could mail me (Kolforn@gmail.com) if you want to use this picture out of the Wik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:-2020-01-01_Brussel_sprouts,_Trimingham,_Norfolk.JPG",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "zucchini": {
    "alt": "Sliced zucchini",
    "title": "Sliced zucchini",
    "author": "WordRidden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/97844767@N00/4820849568",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "tomatoes": {
    "alt": "Ripe red tomatoes on the vine",
    "title": "Tomato je.jpg",
    "author": "Softeis",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 798
  },
  "bell-peppers": {
    "alt": "Red bell peppers, one cut in half",
    "title": "Red bell pepper.jpg",
    "author": "AntanO",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_bell_pepper.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "sweet-corn": {
    "alt": "A husked ear of sweet corn",
    "title": "White Corn on the Cob with husk (27000745034).jpg",
    "author": "Willis Lam",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:White_Corn_on_the_Cob_with_husk_(27000745034).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "green-beans": {
    "alt": "Fresh green beans",
    "title": "Macro of Fresh Green Beans Buncis.jpg",
    "author": "Undeka 11",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Macro_of_Fresh_Green_Beans_Buncis.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "snap-peas": {
    "alt": "Shelled green peas",
    "title": "Peas (484346231).jpg",
    "author": "Ruth Hartnup from Vancouver, Canada",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peas_(484346231).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "radishes": {
    "alt": "A bunch of radishes",
    "title": "Radish 3371103037 4ab07db0bf o.jpg",
    "author": "Self, en:User:Jengod",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Radish_3371103037_4ab07db0bf_o.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "cremini-mushrooms": {
    "alt": "Sliced mushrooms",
    "title": "Sliced mushrooms",
    "author": "kewl",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/58411470@N00/7153397899",
    "via": "Flickr",
    "width": 960,
    "height": 636
  },
  "asparagus": {
    "alt": "Green asparagus spears",
    "title": "Fresh asparagus spears on plate.jpg",
    "author": "Nutrition, Food Safety & Health",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fresh_asparagus_spears_on_plate.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 624
  },
  "kale": {
    "alt": "Washed, chopped kale",
    "title": "Chopped Kale",
    "author": "Shoshanah",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/68737200@N00/8982664552",
    "via": "Flickr",
    "width": 960,
    "height": 640
  },
  "spinach": {
    "alt": "Fresh spinach leaves",
    "title": "Spinach leaves.jpg",
    "author": "Nillerdk",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spinach_leaves.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 708
  },
  "swiss-chard": {
    "alt": "Washed Swiss chard leaves",
    "title": "SwissChardLeaves",
    "author": "YoAmes",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/24013072@N05/4293773119",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "romaine": {
    "alt": "A head of romaine lettuce",
    "title": "Romaine lettuce.jpg",
    "author": "Rainer Zenz",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Romaine_lettuce.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1133
  },
  "yellow-onions": {
    "alt": "Diced onion",
    "title": "diced onions - set aside",
    "author": "austinevan",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/19762676@N00/4034511720",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "garlic": {
    "alt": "Peeled garlic cloves",
    "title": "Peeled garlic cloves.jpg",
    "author": "Fumikas Sagisavas",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peeled_garlic_cloves.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 960
  },
  "leeks": {
    "alt": "Sliced leeks",
    "title": "Free sliced leek close cutting",
    "author": "rawpixel.com",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "sourceUrl": "https://www.rawpixel.com/image/5925519/photo-image-public-domain-green-food",
    "via": "rawpixel",
    "width": 960,
    "height": 640
  },
  "ginger": {
    "alt": "Peeled ginger",
    "title": "Peeled Ginger",
    "author": "Veganbaking.net",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/31104779@N02/6314755173",
    "via": "Flickr",
    "width": 960,
    "height": 640
  },
  "apples": {
    "alt": "A red apple",
    "title": "Red Apple.jpg",
    "author": "Abhijit Tembhekar from Mumbai, India",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_Apple.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 870
  },
  "pears": {
    "alt": "Green and red pears",
    "title": "Four pears.jpg",
    "author": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Four_pears.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 451
  },
  "blueberries": {
    "alt": "Fresh blueberries in a bowl",
    "title": "Dish of blueberries.jpg",
    "author": "Petar Milošević",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dish_of_blueberries.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 721
  },
  "lemons": {
    "alt": "Whole and halved lemons",
    "title": "Lemon.jpg",
    "author": "André Karwath aka Aka",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lemon.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 678
  },
  "greek-yogurt": {
    "alt": "Thick strained yogurt in a bowl",
    "title": "Yoghurt in bowl.jpg",
    "author": "Kris Miller from Issaquah",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yoghurt_in_bowl.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "aged-cheddar": {
    "alt": "A block of aged white cheddar",
    "title": "Somerset-Cheddar.jpg",
    "author": "J.P.Lon",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Somerset-Cheddar.jpg",
    "via": "Wikimedia Commons",
    "width": 879,
    "height": 628
  },
  "feta": {
    "alt": "A wedge of feta",
    "title": "Feta Cheese.jpg",
    "author": "JJ Harrison (https://www.jjharrison.com.au/)",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Feta_Cheese.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 768
  },
  "crushed-tomatoes": {
    "alt": "Smooth crushed tomatoes (passata)",
    "title": "Tomato passata.jpg",
    "author": "Tabby",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tomato_passata.jpg",
    "via": "Wikimedia Commons",
    "width": 930,
    "height": 638
  },
  "chanterelles": {
    "alt": "Chanterelle mushrooms",
    "title": "Chanterelle Mushrooms in Shantullich Wood - geograph.org.uk - 6952952.jpg",
    "author": "Julian Paren",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chanterelle_Mushrooms_in_Shantullich_Wood_-_geograph.org.uk_-_6952952.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "parsley": {
    "alt": "A bunch of flat-leaf parsley",
    "title": "Parsley Leaves.jpg",
    "author": "Etopalrux",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parsley_Leaves.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "cilantro": {
    "alt": "A bunch of fresh cilantro",
    "title": "Coriander Leaves.jpg",
    "author": "Rupeshm364",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coriander_Leaves.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "dill": {
    "alt": "A sprig of fresh dill",
    "title": "Fresh Dill Leaves.JPG",
    "author": "Miansari66",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fresh_Dill_Leaves.JPG",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "wild-sockeye-fillet": {
    "alt": "Raw wild sockeye salmon, cut into a steak and fillets",
    "title": "Oncorhynchus nerka (RFEIMG-0186).jpg",
    "author": "The U.S. Food and Drug Administration",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_(RFEIMG-0186).jpg",
    "via": "Wikimedia Commons",
    "width": 633,
    "height": 438
  },
  "grass-fed-striploin": {
    "alt": "A raw striploin steak",
    "title": "Raw beef steak, 2011.jpg",
    "author": "Jellaluna",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raw_beef_steak,_2011.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "heritage-pork-belly": {
    "alt": "A slab of pork belly",
    "title": "Freshly prepared raw pork belly with red onions and chili peppers.jpg",
    "author": "Shixart1985",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Freshly_prepared_raw_pork_belly_with_red_onions_and_chili_peppers.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 639
  },
  "salsa-verde": {
    "alt": "A bowl of Italian salsa verde",
    "title": "Italian Salsa Verde",
    "author": "TheDeliciousLife",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://www.flickr.com/photos/33715728@N05/4123316559",
    "via": "Flickr",
    "width": 960,
    "height": 720
  },
  "tahini-lemon-sauce": {
    "alt": "A bowl of tahini sauce",
    "title": "Falafels with tarator.jpg",
    "author": "pelican",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Falafels_with_tarator.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "chili-crisp": {
    "alt": "A spoonful of chili crisp",
    "title": "Chili crisp (cropped).jpg",
    "author": "Valereee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chili_crisp_(cropped).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 960
  },
  "warm-spice-blend": {
    "alt": "A ground spice blend",
    "title": "Garam Masala 1.jpg",
    "author": "Gaurav Dhwaj Khadka",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garam_Masala_1.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "miso-ginger-dressing": {
    "alt": "A smooth miso dressing",
    "title": "Miso tahini dressing (43129544912).jpg",
    "author": "Joey Doll",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Miso_tahini_dressing_(43129544912).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 640
  },
  "harissa": {
    "alt": "Harissa in a jar",
    "title": "Harissa in a jar (vertical).jpg",
    "author": "Jules (jules:stonesoup)",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Harissa_in_a_jar_(vertical).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "wild-chanterelles": {
    "alt": "Golden chanterelles growing in moss",
    "title": "2007-07-14 Cantharellus cibarius.jpg",
    "author": "Andreas Kunze",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2007-07-14_Cantharellus_cibarius.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "aged-white-cheddar": {
    "alt": "Slices of sharp white cheddar",
    "title": "2020-03-30 05 45 55 Three cuts of Giant-brand Cracker Cuts of Vermont Sharp Cheddar Cheese in the Dulles section of Sterling, Loudoun County, Virginia.jpg",
    "author": "Famartin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020-03-30_05_45_55_Three_cuts_of_Giant-brand_Cracker_Cuts_of_Vermont_Sharp_Cheddar_Cheese_in_the_Dulles_section_of_Sterling,_Loudoun_County,_Virginia.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "brined-feta": {
    "alt": "A block of feta",
    "title": "Greek feta.jpg",
    "author": "Jon Sullivan",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Greek_feta.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "sourdough-loaf": {
    "alt": "A sourdough loaf",
    "title": "Sourdough Bread Loaf.jpg",
    "author": "Agelaia",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sourdough_Bread_Loaf.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "apple-galette": {
    "alt": "A rustic apple galette",
    "title": "Apple galette (3926990412).jpg",
    "author": "Karen and Brad Emerson",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apple_galette_(3926990412).jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 823
  },
  "berry-crumble": {
    "alt": "A blueberry crumble",
    "title": "Blueberry crumble from Milang Bakery, South Australia.jpg",
    "author": "philip.mallis",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blueberry_crumble_from_Milang_Bakery,_South_Australia.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 720
  },
  "rhubarb-compote": {
    "alt": "Stewed rhubarb compote",
    "title": "Rabarberkompot.jpg",
    "author": "XYZA-2400",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rabarberkompot.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 1280
  },
  "dark-chocolate": {
    "alt": "Squares of dark chocolate",
    "title": "Righteously Raw chocolate.jpg",
    "author": "Mx. Granger",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Righteously_Raw_chocolate.jpg",
    "via": "Wikimedia Commons",
    "width": 960,
    "height": 671
  }
};
