// Search queries for each ingredient and add-on photo, most accurate first:
// the food as Base hands it over (prep form), then the plain ingredient.
export const PHOTO_QUERIES: Record<string, string[]> = {
  'chicken-thighs': ['raw chicken thighs boneless', 'raw chicken thigh'],
  'chicken-breast': ['raw chicken breast', 'chicken breast fillet raw'],
  eggs: ['brown eggs carton', 'chicken eggs'],
  'ground-turkey': ['ground turkey raw', 'minced turkey'],
  'pork-shoulder': ['raw pork meat', 'pork butt raw', 'raw pork cuts'],
  'ground-beef': ['raw ground beef', 'minced beef raw'],
  'firm-tofu': ['tofu block white', 'firm tofu raw', 'tofu cut cubes raw'],
  'sockeye-salmon': ['sockeye salmon fillet', 'raw salmon fillet'],
  chickpeas: ['chickpeas dried', 'Cicer arietinum seeds', 'garbanzo beans'],
  'black-beans': ['black beans dried', 'black turtle beans dry', 'Phaseolus vulgaris black beans'],
  'red-lentils': ['red lentils', 'red lentils dry'],
  'green-lentils': ['green lentils', 'cooked green lentils'],
  'navy-beans': ['navy beans', 'white beans haricot'],
  'brown-rice': ['brown rice uncooked', 'brown rice grains'],
  'rolled-oats': ['rolled oats', 'oat flakes'],
  'pearl-barley': ['pearl barley', 'pearl barley grains'],
  'whole-wheat-pasta': ['whole grain pasta', 'wholemeal penne uncooked', 'wholewheat spaghetti'],
  quinoa: ['quinoa seeds', 'white quinoa uncooked'],
  potatoes: ['potatoes vegetable', 'raw potatoes', 'potato tubers'],
  'sweet-potatoes': ['sweet potato tubers', 'raw sweet potato', 'Ipomoea batatas tuber'],
  carrots: ['carrots vegetable', 'orange carrots bunch', 'carrot batons'],
  beets: ['beetroot vegetable', 'beets bunch', 'red beet roots'],
  parsnips: ['parsnip vegetable', 'parsnips root vegetable', 'Pastinaca sativa root'],
  'butternut-squash': ['butternut squash cubes', 'butternut squash'],
  'green-cabbage': ['shredded cabbage', 'green cabbage'],
  cauliflower: ['cauliflower florets', 'cauliflower'],
  broccoli: ['broccoli florets', 'broccoli'],
  'brussels-sprouts': ['brussels sprouts halved', 'brussels sprouts'],
  zucchini: ['zucchini vegetable', 'courgettes', 'sliced courgette'],
  tomatoes: ['tomatoes on the vine', 'red tomatoes', 'tomato fruit'],
  'bell-peppers': ['red bell pepper', 'red capsicum', 'sliced red pepper'],
  'sweet-corn': ['corn on the cob husked', 'sweet corn cob'],
  'green-beans': ['green beans', 'fresh green beans'],
  'snap-peas': ['shelled green peas', 'fresh peas'],
  radishes: ['radishes', 'red radish bunch'],
  'cremini-mushrooms': ['sliced cremini mushrooms', 'cremini mushrooms'],
  asparagus: ['asparagus spears', 'green asparagus'],
  kale: ['kale leaves', 'curly kale'],
  spinach: ['spinach leaves', 'fresh spinach'],
  'swiss-chard': ['swiss chard', 'rainbow chard'],
  romaine: ['romaine lettuce', 'romaine lettuce leaves'],
  'yellow-onions': ['yellow onion', 'onions vegetable', 'Allium cepa bulbs'],
  garlic: ['peeled garlic cloves', 'garlic bulbs'],
  leeks: ['leek vegetable', 'leeks bunch market', 'Allium porrum'],
  ginger: ['ginger rhizome', 'fresh ginger root', 'Zingiber officinale root'],
  apples: ['red apples', 'apples fruit'],
  pears: ['pears fruit', 'bartlett pears'],
  blueberries: ['blueberries', 'fresh blueberries'],
  lemons: ['lemons', 'lemon fruit'],
  'greek-yogurt': ['yogurt in bowl', 'strained yogurt labneh bowl', 'plain yogurt'],
  'aged-cheddar': ['cheddar cheese wedge', 'cheddar cheese cut', 'mature cheddar'],
  feta: ['feta cheese', 'feta cheese block'],
  'crushed-tomatoes': ['tomato passata', 'tomato puree bowl', 'canned tomatoes open can'],
  chanterelles: ['chanterelles cooking', 'chanterelle mushrooms basket', 'cleaned chanterelles'],
  parsley: ['parsley leaves', 'flat-leaf parsley bunch', 'Petroselinum crispum leaves'],
  cilantro: ['cilantro coriander leaves', 'fresh coriander bunch'],
  dill: ['fresh dill', 'dill herb'],
  'canola-oil': ['cooking oil bottle', 'canola oil'],
  salt: ['salt', 'table salt'],
  // add-ons
  'wild-sockeye-fillet': ['salmon fillet raw', 'sockeye salmon'],
  'grass-fed-striploin': ['raw beef steak', 'sirloin steak raw', 'beef striploin'],
  'heritage-pork-belly': ['raw pork belly', 'pork belly skin'],
  'salsa-verde': ['salsa verde herbs capers', 'green sauce parsley', 'pesto bowl'],
  'tahini-lemon-sauce': ['tahini sauce bowl', 'tarator sauce', 'tahini dip'],
  'chili-crisp': ['chili crisp', 'chili oil jar'],
  'warm-spice-blend': ['ground spices', 'spice mix ground cumin coriander'],
  'miso-ginger-dressing': ['miso dressing', 'white miso'],
  harissa: ['harissa', 'harissa paste'],
  'wild-chanterelles': ['chanterelle mushrooms', 'Cantharellus formosus'],
  'aged-white-cheddar': ['white cheddar cheese block', 'cheddar cheese wedge'],
  'brined-feta': ['feta in brine', 'feta cheese'],
  'sourdough-loaf': ['sourdough bread loaf', 'sourdough bread'],
  'apple-galette': ['apple galette', 'apple tart rustic'],
  'berry-crumble': ['blueberry crumble', 'berry crumble'],
  'rhubarb-compote': ['rhubarb compote', 'stewed rhubarb'],
  'dark-chocolate': ['dark chocolate pieces', 'chocolate bar broken', 'dark chocolate squares'],
};
