// Search queries for each ingredient and add-on photo, most accurate first:
// the food as Base hands it over (prep form), then the plain ingredient.
export const PHOTO_QUERIES: Record<string, string[]> = {
  'chicken-thighs': ['raw chicken thighs boneless', 'raw chicken thigh'],
  'chicken-breast': ['raw chicken breast', 'chicken breast fillet raw'],
  eggs: ['brown eggs carton', 'chicken eggs'],
  'ground-turkey': ['ground turkey raw', 'minced turkey'],
  'pork-shoulder': ['raw pork shoulder', 'pork shoulder butt raw'],
  'ground-beef': ['raw ground beef', 'minced beef raw'],
  'firm-tofu': ['firm tofu block', 'tofu cubes'],
  'sockeye-salmon': ['sockeye salmon fillet', 'raw salmon fillet'],
  chickpeas: ['cooked chickpeas bowl', 'chickpeas'],
  'black-beans': ['cooked black beans', 'black turtle beans'],
  'red-lentils': ['red lentils', 'red lentils dry'],
  'green-lentils': ['green lentils', 'cooked green lentils'],
  'navy-beans': ['navy beans', 'white beans haricot'],
  'brown-rice': ['brown rice uncooked', 'brown rice grains'],
  'rolled-oats': ['rolled oats', 'oat flakes'],
  'pearl-barley': ['pearl barley', 'pearl barley grains'],
  'whole-wheat-pasta': ['whole wheat pasta', 'wholemeal penne'],
  quinoa: ['quinoa seeds', 'white quinoa uncooked'],
  potatoes: ['potato wedges raw', 'potatoes'],
  'sweet-potatoes': ['sweet potato cubes', 'sweet potatoes'],
  carrots: ['carrot sticks', 'carrots'],
  beets: ['roasted beetroot', 'beetroot'],
  parsnips: ['parsnips', 'parsnip root'],
  'butternut-squash': ['butternut squash cubes', 'butternut squash'],
  'green-cabbage': ['shredded cabbage', 'green cabbage'],
  cauliflower: ['cauliflower florets', 'cauliflower'],
  broccoli: ['broccoli florets', 'broccoli'],
  'brussels-sprouts': ['brussels sprouts halved', 'brussels sprouts'],
  zucchini: ['sliced zucchini', 'zucchini courgette'],
  tomatoes: ['ripe tomatoes', 'tomatoes'],
  'bell-peppers': ['red bell pepper strips', 'red bell pepper'],
  'sweet-corn': ['corn on the cob husked', 'sweet corn cob'],
  'green-beans': ['green beans', 'fresh green beans'],
  'snap-peas': ['shelled green peas', 'fresh peas'],
  radishes: ['radishes', 'red radish bunch'],
  'cremini-mushrooms': ['sliced cremini mushrooms', 'cremini mushrooms'],
  asparagus: ['asparagus spears', 'green asparagus'],
  kale: ['kale leaves', 'curly kale'],
  spinach: ['spinach leaves', 'fresh spinach'],
  'swiss-chard': ['swiss chard', 'rainbow chard'],
  romaine: ['romaine lettuce', 'romaine lettuce leaves'],
  'yellow-onions': ['diced onion', 'yellow onions'],
  garlic: ['peeled garlic cloves', 'garlic bulbs'],
  leeks: ['sliced leeks', 'leeks'],
  ginger: ['ginger root', 'fresh ginger rhizome'],
  apples: ['red apples', 'apples fruit'],
  pears: ['pears fruit', 'bartlett pears'],
  blueberries: ['blueberries', 'fresh blueberries'],
  lemons: ['lemons', 'lemon fruit'],
  'greek-yogurt': ['greek yogurt bowl', 'strained yogurt'],
  'aged-cheddar': ['cheddar cheese block', 'aged cheddar'],
  feta: ['feta cheese', 'feta cheese block'],
  'crushed-tomatoes': ['crushed tomatoes', 'canned tomatoes'],
  chanterelles: ['chanterelle mushrooms', 'Cantharellus cibarius basket'],
  parsley: ['flat leaf parsley', 'parsley bunch'],
  cilantro: ['cilantro coriander leaves', 'fresh coriander bunch'],
  dill: ['fresh dill', 'dill herb'],
  'canola-oil': ['cooking oil bottle', 'canola oil'],
  salt: ['salt', 'table salt'],
  // add-ons
  'wild-sockeye-fillet': ['sockeye salmon fillet', 'wild salmon fillet'],
  'grass-fed-striploin': ['striploin steak raw', 'strip steak raw'],
  'heritage-pork-belly': ['raw pork belly', 'pork belly skin'],
  'salsa-verde': ['salsa verde italian', 'salsa verde sauce'],
  'tahini-lemon-sauce': ['tahini sauce', 'tahini'],
  'chili-crisp': ['chili crisp', 'chili oil jar'],
  'warm-spice-blend': ['ground spices', 'spice mix ground cumin coriander'],
  'miso-ginger-dressing': ['miso dressing', 'white miso'],
  harissa: ['harissa', 'harissa paste'],
  'wild-chanterelles': ['chanterelle mushrooms', 'Cantharellus formosus'],
  'aged-white-cheddar': ['white cheddar cheese', 'cheddar cheese'],
  'brined-feta': ['feta in brine', 'feta cheese'],
  'sourdough-loaf': ['sourdough bread loaf', 'sourdough bread'],
  'apple-galette': ['apple galette', 'apple tart rustic'],
  'berry-crumble': ['blueberry crumble', 'berry crumble'],
  'rhubarb-compote': ['rhubarb compote', 'stewed rhubarb'],
  'dark-chocolate': ['dark chocolate bar', 'dark chocolate'],
};
