// Search queries for each ingredient and add-on photo, most accurate first:
// the food as Base hands it over (prep form), then the plain ingredient.
export const PHOTO_QUERIES: Record<string, string[]> = {
  'chicken-thighs': ['raw chicken thighs boneless', 'raw chicken thigh'],
  'chicken-breast': ['raw chicken breast', 'chicken breast fillet raw'],
  eggs: ['brown eggs carton', 'chicken eggs'],
  'ground-turkey': ['ground turkey meat', 'raw turkey mince', 'minced poultry meat raw'],
  'pork-shoulder': ['raw pork meat', 'pork butt raw', 'raw pork cuts'],
  'ground-beef': ['raw ground beef', 'minced beef raw'],
  'firm-tofu': ['tofu', 'block of tofu', 'silken firm tofu'],
  'sockeye-salmon': ['sockeye salmon meat', 'red salmon fillet', 'Oncorhynchus nerka fillet', 'sockeye salmon raw'],
  chickpeas: ['chickpeas dried', 'Cicer arietinum seeds', 'garbanzo beans'],
  'black-beans': ['black beans', 'black bean seeds', 'frijoles negros'],
  'red-lentils': ['red lentils', 'red lentils dry'],
  'green-lentils': ['green lentils', 'cooked green lentils'],
  'navy-beans': ['navy beans', 'white beans haricot'],
  'brown-rice': ['brown rice uncooked', 'brown rice grains'],
  'rolled-oats': ['rolled oats', 'oat flakes'],
  'pearl-barley': ['pearl barley', 'pearl barley grains'],
  'whole-wheat-pasta': ['whole wheat pasta dry', 'brown pasta uncooked', 'whole wheat fusilli'],
  quinoa: ['quinoa seeds', 'white quinoa uncooked'],
  potatoes: ['potatoes vegetable', 'raw potatoes', 'potato tubers'],
  'sweet-potatoes': ['sweet potato tubers', 'raw sweet potato', 'Ipomoea batatas tuber'],
  carrots: ['carrots vegetable', 'orange carrots bunch', 'carrot batons'],
  beets: ['beetroot vegetable', 'beets bunch', 'red beet roots'],
  parsnips: ['parsnips', 'parsnip harvest', 'parsnips market'],
  'butternut-squash': ['butternut squash cubes', 'butternut squash'],
  'green-cabbage': ['shredded cabbage', 'green cabbage'],
  cauliflower: ['cauliflower florets', 'cauliflower'],
  broccoli: ['broccoli florets', 'broccoli'],
  'brussels-sprouts': ['brussels sprouts halved', 'brussels sprouts'],
  zucchini: ['zucchini vegetable', 'courgettes', 'sliced courgette'],
  tomatoes: ['tomatoes on the vine', 'red tomatoes', 'tomato fruit'],
  'bell-peppers': ['red bell pepper', 'red capsicum', 'sliced red pepper'],
  'sweet-corn': ['corn on the cob husked', 'sweet corn cob'],
  'green-beans': ['green beans', 'fresh green beans'],
  'snap-peas': ['shelled green peas', 'fresh peas'],
  radishes: ['radishes', 'red radish bunch'],
  'cremini-mushrooms': ['sliced cremini mushrooms', 'cremini mushrooms'],
  asparagus: ['asparagus spears', 'green asparagus'],
  kale: ['kale leaves', 'curly kale'],
  spinach: ['spinach leaves', 'fresh spinach'],
  'swiss-chard': ['swiss chard', 'rainbow chard'],
  romaine: ['romaine lettuce', 'romaine lettuce leaves'],
  'yellow-onions': ['yellow onion', 'onions vegetable', 'Allium cepa bulbs'],
  garlic: ['peeled garlic cloves', 'garlic bulbs'],
  leeks: ['leek vegetable', 'leeks bunch market', 'Allium porrum'],
  ginger: ['ginger rhizome', 'fresh ginger root', 'Zingiber officinale root'],
  apples: ['red apples', 'apples fruit'],
  pears: ['pears fruit', 'bartlett pears'],
  blueberries: ['blueberries', 'fresh blueberries'],
  lemons: ['lemons', 'lemon fruit'],
  'greek-yogurt': ['yogurt in bowl', 'strained yogurt labneh bowl', 'plain yogurt'],
  'aged-cheddar': ['cheddar cheese wedge', 'cheddar cheese cut', 'mature cheddar'],
  feta: ['feta cheese', 'feta cheese block'],
  'crushed-tomatoes': ['tomato passata', 'tomato puree bowl', 'canned tomatoes open can'],
  chanterelles: ['chanterelles cooking', 'chanterelle mushrooms basket', 'cleaned chanterelles'],
  parsley: ['parsley leaves', 'flat-leaf parsley bunch', 'Petroselinum crispum leaves'],
  cilantro: ['cilantro coriander leaves', 'fresh coriander bunch'],
  dill: ['fresh dill', 'dill herb'],
  'canola-oil': ['cooking oil bottle', 'canola oil'],
  salt: ['salt', 'table salt'],
  // add-ons
  'wild-sockeye-fillet': ['sockeye fillet', 'wild sockeye salmon fillet', 'smoked sockeye'],
  'grass-fed-striploin': ['raw beef steak', 'sirloin steak raw', 'beef striploin'],
  'heritage-pork-belly': ['raw pork belly', 'pork belly skin'],
  'salsa-verde': ['salsa verde', 'italian green sauce', 'herb sauce parsley capers'],
  'tahini-lemon-sauce': ['tahini sauce bowl', 'tarator sauce', 'tahini dip'],
  'chili-crisp': ['chili crisp', 'chili oil jar'],
  'warm-spice-blend': ['ground spices', 'spice mix ground cumin coriander'],
  'miso-ginger-dressing': ['miso dressing', 'white miso'],
  harissa: ['harissa', 'harissa paste'],
  'wild-chanterelles': ['chanterelle mushrooms', 'Cantharellus formosus'],
  'aged-white-cheddar': ['white cheddar cheese block', 'cheddar cheese wedge'],
  'brined-feta': ['feta in brine', 'feta cheese'],
  'sourdough-loaf': ['sourdough bread loaf', 'sourdough bread'],
  'apple-galette': ['apple galette', 'apple tart rustic'],
  'berry-crumble': ['blueberry crumble', 'berry crumble'],
  'rhubarb-compote': ['rhubarb compote', 'stewed rhubarb'],
  'dark-chocolate': ['dark chocolate pieces', 'chocolate bar broken', 'dark chocolate squares'],
};

// The food as Base hands it over (washed, cut or cooked), for the bowls on the
// counter. Fetched with PHOTO_SET=prep.
export const PREP_QUERIES: Record<string, string[]> = {
  chickpeas: ['cooked chickpeas', 'boiled chickpeas', 'chickpeas drained'],
  'black-beans': ['cooked black beans', 'boiled black beans', 'black beans bowl'],
  'green-lentils': ['cooked lentils', 'boiled green lentils', 'cooked brown lentils'],
  'navy-beans': ['cooked white beans', 'cooked navy beans', 'cannellini beans cooked'],
  potatoes: ['potato wedges raw', 'cut potatoes', 'potatoes cut into wedges', 'peeled potatoes cut'],
  'sweet-potatoes': ['sweet potato cubes raw', 'diced sweet potato', 'peeled sweet potato'],
  carrots: ['carrot sticks', 'carrot batons', 'julienned carrots', 'cut carrots'],
  parsnips: ['parsnip sticks', 'cut parsnips', 'peeled parsnips'],
  beets: ['roasted beetroot peeled', 'cooked beetroot', 'boiled beets peeled'],
  zucchini: ['sliced zucchini', 'zucchini slices', 'courgette slices raw'],
  'bell-peppers': ['red pepper strips', 'sliced red bell pepper', 'bell pepper slices'],
  'cremini-mushrooms': ['sliced mushrooms', 'sliced brown mushrooms', 'mushroom slices raw'],
  kale: ['chopped kale', 'torn kale leaves', 'kale leaves washed'],
  'yellow-onions': ['diced onion', 'chopped onion', 'onion dice'],
  leeks: ['sliced leeks', 'chopped leek', 'leek rings'],
  ginger: ['peeled ginger', 'ginger root peeled', 'sliced ginger'],
  'greek-yogurt': ['yogurt glass jar', 'yoghurt in jar', 'strained yogurt jar'],
  'brussels-sprouts': ['halved brussels sprouts raw', 'brussels sprouts cut in half', 'trimmed brussels sprouts'],
  'butternut-squash': ['butternut squash cubes', 'cubed squash raw', 'diced butternut'],
  'swiss-chard': ['chopped swiss chard', 'chard leaves washed', 'swiss chard stems leaves'],
  'green-beans': ['trimmed green beans', 'green beans topped and tailed'],
  'firm-tofu': ['pressed tofu', 'tofu cubes', 'cubed tofu raw'],
  'whole-wheat-pasta': ['whole wheat penne', 'wholemeal pasta', 'whole grain spaghetti dry'],
  'salsa-verde': ['bagnet verd', 'salsa verde italiana', 'sauce verte', 'green sauce bowl parsley'],
};

// Finished dishes for recipe pages: a similar cooked meal, not the raw ingredients.
// Fetched with PHOTO_SET=dish.
export const DISH_QUERIES: Record<string, string[]> = {
  'crispy-chickpea-potato-bowl': ['roasted chickpea potato bowl', 'crispy chickpeas roasted potatoes', 'chickpea buddha bowl'],
  'green-chicken-curry': ['thai green chicken curry', 'green curry chicken', 'green curry'],
  'breakfast-hash': ['breakfast hash fried egg', 'potato hash eggs skillet', 'breakfast hash'],
  'roasted-cauliflower-barley-salad': ['roasted cauliflower grain salad', 'barley salad', 'roasted cauliflower salad'],
  'lemon-garlic-chicken-sheet-pan': ['roast chicken thighs', 'chicken traybake', 'sheet pan chicken', 'roasted chicken potatoes', 'baked chicken thighs'],
  'chicken-barley-soup': ['chicken barley soup', 'chicken and barley soup', 'chicken vegetable barley soup'],
  'spiced-carrot-soup': ['carrot soup yogurt', 'spiced carrot soup', 'carrot soup bowl'],
  'eggs-garlicky-greens-chickpeas': ['eggs and greens', 'fried egg kale', 'shakshuka greens', 'egg spinach skillet', 'eggs florentine'],
  'cauliflower-potato-curry': ['aloo gobi', 'cauliflower potato curry', 'aloo gobhi'],
  'chicken-barley-bowls-lemon-yogurt': ['chicken grain bowl', 'chicken quinoa bowl', 'grilled chicken salad bowl', 'chicken rice bowl vegetables'],
  'squash-black-bean-chili': ['black bean squash chili', 'vegetarian black bean chili', 'butternut squash chili'],
  'crispy-tofu-cabbage-stir-fry': ['tofu stir fry', 'fried tofu vegetables', 'tofu and cabbage', 'crispy tofu'],
  'kale-barley-minestrone': ['minestrone kale', 'minestrone soup', 'kale vegetable soup'],
  'charred-tomato-black-bean-bowls': ['black bean rice bowl tomato', 'black bean bowl', 'black beans rice salsa'],
  'asparagus-spinach-barley-risotto': ['barley risotto asparagus', 'orzotto', 'asparagus risotto'],
  'parsnip-cabbage-mushroom-tray': ['roasted parsnips', 'roasted root vegetables', 'roasted vegetables tray', 'roasted cabbage'],
};

// Better-matching searches for Openverse (mostly Flickr), which has far more home-kitchen food photos.
export const OPENVERSE_EXTRA: Record<string, string[]> = {
  'salsa-verde': ['salsa verde bowl parsley capers', 'italian salsa verde', 'green herb sauce'],
  'bell-peppers': ['sliced red peppers', 'red pepper strips'],
};
